name: Bug Report (form)
description: Scanpy doesn’t do what it should? Please help us fix it!
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Scanpy doesn’t do what it should? Please help us fix it!

        Before openning a new issue, we'd like you to make sure it hasn't been addressed or reported before. Please:

        - Check that this issue has not already been reported.
        - Confirm this bug exists on the latest version of scanpy.
        - (optional) Confirm this bug exists on the master branch of scanpy.
  - type: textarea
    id: reproducer
    attributes:
      label: Reproducible example
      description: |
        A small example that can reproduce this bug.

        **Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.
      placeholder: |
        ```python
        ```
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
      placeholder: |
        A bug happened! Unexpectedly!
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version and environment info
      description: What version of Scanpy are you using, and what does your environment look like?
      render: Text
      placeholder: Paste output of `sc.logging.print_versions()` here!
    validations:
      required: true
