name: Bug Report
description: Scanpy doesn’t do what it should? Please help us fix it!
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Scanpy doesn’t do what it should? Please help us fix it!
  - type: textarea
    id: reproducer
    attributes:
      label: Reproducible example
      description: |
        A small example that can reproduce this bug.

        **Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.
      value: |
        ```python
        ```
      placeholder: |
        ```python
        {your code here}
        ```

        ```pytb
        {The error or traceback, if applicable}
        ```
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version and environment info
      description: What version of Scanpy are you using, and what does your environment look like?
      render: Text
      placeholder: Paste output of `sc.logging.print_versions()` here!
    validations:
      required: true
